<a href="https://colab.research.google.com/github/Meghali54/AI_Browser_Automation/blob/main/SQL_Movie_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# SQL Movie Rental Analysis

This notebook analyzes the given SQL data using SQLite and Python (pandas).

In [1]:
import sqlite3
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
conn = sqlite3.connect(':memory:')
cursor = conn.cursor()

In [3]:
cursor.executescript("""
DROP TABLE IF EXISTS invoice;
DROP TABLE IF EXISTS movie;
DROP TABLE IF EXISTS customer;

CREATE TABLE customer(
    cust_id TEXT PRIMARY KEY,
    f_name TEXT,
    l_name TEXT,
    area TEXT,
    ph_no INTEGER
);

CREATE TABLE movie(
    mv_no INTEGER PRIMARY KEY,
    title TEXT,
    type TEXT,
    star TEXT,
    price INTEGER
);

CREATE TABLE invoice(
    inv_no TEXT PRIMARY KEY,
    mv_no INTEGER,
    cust_id TEXT,
    issue_date TEXT,
    return_date TEXT,
    FOREIGN KEY(mv_no) REFERENCES movie(mv_no),
    FOREIGN KEY(cust_id) REFERENCES customer(cust_id)
);
""")
conn.commit()

In [4]:
cursor.executescript("""
INSERT INTO customer VALUES('a01','Ivan','Bayross','sa',6125467);
INSERT INTO customer VALUES('a02','Vandana','Saiteal','mu',5560379);
INSERT INTO customer VALUES('a03','Pramedo','Jauguste','da',4560389);
INSERT INTO customer VALUES('a04','Basu','Navindgi','ba',6125401);
INSERT INTO customer VALUES('a05','Ravi','Sreedharm','na',NULL);
INSERT INTO customer VALUES('a06','Rukmini',NULL,'gh',512574);

INSERT INTO movie VALUES(1,'Bloody','Action','Jacki Chang',181);
INSERT INTO movie VALUES(2,'The Firm','Thriller','Tom Cruise',200);
INSERT INTO movie VALUES(3,'Pretty Woman','Romance','Richard Gere',151);
INSERT INTO movie VALUES(4,'Home Alone','Comedy','Macaulay Culkin',150);
INSERT INTO movie VALUES(5,'The Fugitive','Thriller','Marison Ford',200);
INSERT INTO movie VALUES(6,'Coma','Suspense','Michael Douglas',100);
INSERT INTO movie VALUES(7,'Dracula','Horror','Grey Oldman',100);
INSERT INTO movie VALUES(8,'Quick Change','Comedy','Bill Mauray',100);
INSERT INTO movie VALUES(9,'Gone with the wind','Action','Clark Gable',200);
INSERT INTO movie VALUES(10,'Carry on Doctor','Comedy','Leslie Philips',100);

INSERT INTO invoice VALUES('i01',4,'a01','1993-07-23','1993-07-25');
INSERT INTO invoice VALUES('i02',3,'a02','1993-08-12','1993-08-15');
INSERT INTO invoice VALUES('i03',1,'a02','1993-08-15','1993-08-18');
INSERT INTO invoice VALUES('i04',6,'a03','1993-09-10','1993-09-13');
INSERT INTO invoice VALUES('i05',7,'a04','1993-08-05','1993-08-08');
INSERT INTO invoice VALUES('i06',2,'a06','1993-09-18','1993-09-21');
INSERT INTO invoice VALUES('i07',9,'a05','1993-07-07','1993-07-10');
INSERT INTO invoice VALUES('i08',9,'a01','1993-08-11','1993-08-14');
INSERT INTO invoice VALUES('i09',5,'a03','1993-07-06','1993-07-09');
INSERT INTO invoice VALUES('i10',8,'a06','1993-09-03','1993-09-06');
""")
conn.commit()

In [6]:
customer_df = pd.read_sql('SELECT * FROM customer', conn)
movie_df = pd.read_sql('SELECT * FROM movie', conn)
invoice_df = pd.read_sql('SELECT * FROM invoice', conn)

display(customer_df.head())
display(movie_df.head())
display(invoice_df.head())

  cust_id   f_name     l_name area      ph_no
0     a01     Ivan    Bayross   sa  6125467.0
1     a02  Vandana    Saiteal   mu  5560379.0
2     a03  Pramedo   Jauguste   da  4560389.0
3     a04     Basu   Navindgi   ba  6125401.0
4     a05     Ravi  Sreedharm   na        NaN

   mv_no         title      type             star  price
0      1        Bloody    Action      Jacki Chang    181
1      2      The Firm  Thriller       Tom Cruise    200
2      3  Pretty Woman   Romance     Richard Gere    151
3      4    Home Alone    Comedy  Macaulay Culkin    150
4      5  The Fugitive  Thriller     Marison Ford    200

  inv_no  mv_no cust_id  issue_date return_date
0    i01      4     a01  1993-07-23  1993-07-25
1    i02      3     a02  1993-08-12  1993-08-15
2    i03      1     a02  1993-08-15  1993-08-18
3    i04      6     a03  1993-09-10  1993-09-13
4    i05      7     a04  1993-08-05  1993-08-08

In [7]:
query = '''
SELECT m.type, COUNT(*) AS total_rentals
FROM movie m
JOIN invoice i ON m.mv_no = i.mv_no
GROUP BY m.type
'''
rentals_by_type = pd.read_sql(query, conn)
rentals_by_type

       type  total_rentals
0    Action              3
1    Comedy              2
2    Horror              1
3   Romance              1
4  Suspense              1
5  Thriller              2

In [ ]:
rentals_by_type.plot(kind='bar', x='type', y='total_rentals', legend=False)
plt.title('Movie Rentals by Type')
plt.ylabel('Total Rentals')
plt.show()

Select all rows of Customer Table

In [8]:
customer_all_rows_df = pd.read_sql('SELECT * FROM customer', conn)
display(customer_all_rows_df)

  cust_id   f_name     l_name area      ph_no
0     a01     Ivan    Bayross   sa  6125467.0
1     a02  Vandana    Saiteal   mu  5560379.0
2     a03  Pramedo   Jauguste   da  4560389.0
3     a04     Basu   Navindgi   ba  6125401.0
4     a05     Ravi  Sreedharm   na        NaN
5     a06  Rukmini       None   gh   512574.0